version: '3.8'

services:
  front:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - api

  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: 'mongo:4.4.4'
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: 'mongo-express'
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
    depends_on:
      - mongo

  api:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - redis

volumes:
  redis-data:
  mongo-data:
