version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

  api:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=jHg23!23FeZ?6G2
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
