version: '3.8'

services:
  money-count-front:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - money-count-api

  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: 'mongo:4.4.4'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  money-count-api:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - redis
      - mongo

volumes:
  redis-data:
  mongo-data:
