version: '3.8'

services:
  front:
    image: totomadme/money-count-front:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - api

  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: 'mongo:4.4.4'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    image: totomadme/money-count-api:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=6b99969d371dfa661379a943e7de22455d993814399e045dda3307506865c117fa9c6a636500437021520a3255aa6e1b46567927ac1d4280c925e5f64fd9859
    depends_on:
      - redis
      - mongo

volumes:
  redis-data:
  mongo-data:
